#!/usr/bin/env bash
#PBS -N stretcher_variant_calling
#PBS -l walltime=200:00:00
#PBS -l select=1:ncpus=1:mem=4gb:scratch_local=200gb
#PBS -j oe

# ==========================================
# 1. INPUT ARGUMENTS & USAGE EXAMPLE
# ==========================================
# Example Run Command:
# qsub script.sh -v CHR_ID="Sample_chr3",S1="PAN027",S2="PAN010",OUT="/path/to/results"
#
# Arguments provided via -v (PBS variables):
# CHR_ID - Unique ID for the output file (e.g., PAN027.chr3.maternal_2)
# S1     - Exact name of sequence 1 in the BED/FASTA (e.g., PAN027.chr3.maternal)
# S2     - Exact name of sequence 2 in the BED/FASTA (e.g., PAN010.chr3.haplotype2)
# OUT    - Path to the final output directory

if [ -z "$CHR_ID" ] || [ -z "$S1" ] || [ -z "$S2" ] || [ -z "$OUT" ]; then
    echo "Error: Missing required variables CHR_ID, S1, S2, or OUT."
    echo "Usage: qsub $0 -v CHR_ID=\"ID\",S1=\"seq1\",S2=\"seq2\",OUT=\"/path\""
    exit 1
fi

# Map variables for clarity
SEQ1_NAME=$S1
SEQ2_NAME=$S2
OUT_DIR=$OUT
mkdir -p "$OUT_DIR"

# ==========================================
# 2. ENVIRONMENT SETUP (USER DEFINED)
# ==========================================
PROJ_DIR="/storage/praha5-elixir/projects/bioinf-fi/polakova/BP"

# Load required tools
module load emboss
module load bedtools

# Validation: Check if tools are accessible
for TOOL in stretcher straln bedtools; do
    if ! command -v $TOOL &> /dev/null; then
        echo "Error: $TOOL not found in PATH."
        exit 1
    fi
done

# ==========================================
# 3. PREPARE INPUTS & OFFSETS (SCRATCH)
# ==========================================
echo "Moving to scratch: $SCRATCHDIR"
cd "$SCRATCHDIR" || exit 1

# Input data mapping
BED_OFFSETS="$PROJ_DIR/__data/pedigree/annotations_v1.1/centromeres_bed/offsets.bed"
BED_GAPS="$PROJ_DIR/__data/pedigree/annotations_v1.1/gaps_all.bed"
BED_PROBLEMATIC="$PROJ_DIR/__data/pedigree/annotations_v1.1/problematic_all.bed"

# Note: Update these paths if your FASTA filenames differ from the sequence names
FASTA_REF="$PROJ_DIR/__data/pedigree/extracted_centromeres_v1.1/${S1}.fasta"
FASTA_MUT="$PROJ_DIR/__data/pedigree/extracted_centromeres_v1.1/${S2}.fasta" # Example logic

# Extract offsets for alignment coordination
OFFSET1=$(awk -v chr="$SEQ1_NAME" '$1 == chr {print $2}' "$BED_OFFSETS" | head -n 1)
OFFSET2=$(awk -v chr="$SEQ2_NAME" '$1 == chr {print $2}' "$BED_OFFSETS" | head -n 1)

if [ -z "$OFFSET1" ] || [ -z "$OFFSET2" ]; then
    echo "ERROR: Offset not found for $SEQ1_NAME or $SEQ2_NAME"
    exit 1
fi

cp "$FASTA_REF" ./ref.fasta
cp "$FASTA_MUT" ./mut.fasta

# ==========================================
# 4. RUN ALIGNMENT (STRETCHER)
# ==========================================
echo "Running EMBOSS stretcher..."
stretcher -auto -asequence ./ref.fasta -bsequence ./mut.fasta \
          -aformat markx0 -gapextend 4 -gapopen 16 -outfile "./alignment.aln"

STRETCHER_EXIT=$?

# ==========================================
# 5. PARSE AND FILTER VARIANTS
# ==========================================
if [ $STRETCHER_EXIT -eq 0 ]; then
    echo "Parsing alignment with straln..."
    mkdir -p "./straln_results"

    straln "./alignment.aln" \
        -s1 "$SEQ1_NAME" \
        -s2 "$SEQ2_NAME" \
        -off1 "$OFFSET1" \
        -off2 "$OFFSET2" \
        -o "./straln_results"

    RAW_STRALN=$(ls ./straln_results/*.tsv 2>/dev/null | head -n 1)

    if [ -f "$RAW_STRALN" ]; then
        echo "Filtering variants using BEDtools..."

        # Prepare relevant BED filters for these sequences
        grep -E "($SEQ1_NAME|$SEQ2_NAME)" "$BED_PROBLEMATIC" > relevant_probs.bed
        grep -E "($SEQ1_NAME|$SEQ2_NAME)" "$BED_GAPS" > relevant_gaps.bed

        # Step-wise filtering: -v removes overlapping regions
        bedtools intersect -v -a "$RAW_STRALN" -b relevant_probs.bed > tmp_no_prob.tsv
        bedtools intersect -v -a tmp_no_prob.tsv -b relevant_gaps.bed > filtered_final.tsv

        # Save results
        cp "./alignment.aln" "$OUT_DIR/${CHR_ID}.aln"
        cp -r "./straln_results" "$OUT_DIR/straln_raw_all"
        cp "./filtered_final.tsv" "$OUT_DIR/${CHR_ID}.filtered.tsv"

        echo "Pipeline successful. Results in: $OUT_DIR"
    else
        echo "Error: No TSV output generated by straln."
        exit 1
    fi
else
    echo "Error: Stretcher failed with exit code $STRETCHER_EXIT"
    exit 1
fi