#!/usr/bin/env bash
#PBS -N stretcher_variant_calling
#PBS -l walltime=200:00:00
#PBS -l select=1:ncpus=1:mem=4gb:scratch_local=200gb
#PBS -j oe

# ==============================================================================
# DOCUMENTATION:
# ==============================================================================
# 1. OFFSET EXTRACTION:
#    Extracts genomic offsets from BED files by matching the sequence name
#    against the 1st column of the BED.
#
# 2. DOUBLE-SIDED FILTERING STRATEGY (bedtools):
#    Stage 1: Filter Seq1_Pos against PROBLEMATIC and GAPS (BED_PROBLEMATIC, BED_GAPS).
#    Stage 2: Filter Seq2_Pos against PROBLEMATIC and GAPS (BED_PROBLEMATIC, BED_GAPS).
#
# 3. COORDINATE MAPPING:
#    TSV Column 1 = Sequence 1 name.
#    TSV Column 2 = Sequence 1 start position.
#    TSV Column 3 = Sequence 1 end position.
#    TSV Column 4 = Sequence 2 name.
#    TSV Column 5 = Sequence 2 start position.
#    TSV Column 6 = Sequence 2 end position.
#
# USAGE:
#    1. Copy config.example.sh to config.sh and fill in your paths.
#    2. Submit with: qsub align_call.sh
#
# NOTE: PBS directives are parsed before the shell runs and cannot use
#       variables, so any PBS-level paths must be set directly in the header.
# ==============================================================================

# --- LOAD USER CONFIGURATION ---
SCRIPT_DIR="$(dirname "$0")"
CONFIG="$SCRIPT_DIR/config.sh"
if [[ ! -f "$CONFIG" ]]; then
    echo "ERROR: config.sh not found. Copy config.example.sh to config.sh and fill in your paths."
    exit 1
fi
# shellcheck source=config.sh
source "$CONFIG"

# ==============================================================================
# 1. VALIDATE CONFIGURATION
# ==============================================================================
if [ -z "$CHR_ID" ] || [ -z "$S1" ] || [ -z "$S2" ] || [ -z "$OUT" ]; then
    echo "ERROR: Missing required variables CHR_ID, S1, S2, or OUT in config.sh."
    exit 1
fi

mkdir -p "$OUT"

# ==============================================================================
# 2. ENVIRONMENT SETUP
# ==============================================================================
module load emboss

for TOOL in stretcher straln bedtools; do
    if ! command -v "$TOOL" &> /dev/null; then
        echo "ERROR: $TOOL not found in PATH."
        exit 1
    fi
done

# ==============================================================================
# 3. PREPARE INPUTS & OFFSETS
# ==============================================================================
echo "Moving to scratch: $SCRATCHDIR"
cd "$SCRATCHDIR" || exit 1

cp "$FASTA_REF" ./ref.fasta
cp "$FASTA_MUT" ./mut.fasta

# Extract offsets for both sequences from the BED file
OFFSET1=$(awk -v chr="$S1" '$1 == chr {print $2; exit}' "$BED_OFFSETS")
OFFSET2=$(awk -v chr="$S2" '$1 == chr {print $2; exit}' "$BED_OFFSETS")

# Default to 0 if offset is not found
OFFSET1=${OFFSET1:-0}
OFFSET2=${OFFSET2:-0}

echo "Offsets detected: S1=$OFFSET1, S2=$OFFSET2"

# ==============================================================================
# 4. RUN ALIGNMENT (STRETCHER)
# ==============================================================================
echo "Running EMBOSS stretcher..."
stretcher -auto \
    -asequence ref.fasta \
    -bsequence mut.fasta \
    -aformat markx0 \
    -gapextend 4 \
    -gapopen 16 \
    -outfile "./alignment.aln"

STRETCHER_EXIT=$?

if [ $STRETCHER_EXIT -ne 0 ]; then
    echo "ERROR: Stretcher failed with exit code $STRETCHER_EXIT"
    exit 1
fi

# Check that stretcher produced a non-empty alignment file
if [[ ! -s "./alignment.aln" ]]; then
    echo "ERROR: Stretcher produced an empty alignment file."
    exit 1
fi

# ==============================================================================
# 5. PARSE VARIANTS (STRALN)
# ==============================================================================
echo "Parsing alignment with straln..."
mkdir -p "./straln_results"

straln "./alignment.aln" \
    -s1 "$S1" \
    -s2 "$S2" \
    -off1 "$OFFSET1" \
    -off2 "$OFFSET2" \
    -o "./straln_results"

RAW_STRALN=$(ls ./straln_results/*.bedpe 2>/dev/null | head -n 1)

if [[ ! -f "$RAW_STRALN" ]]; then
    echo "ERROR: No BEDPE output generated by straln."
    exit 1
fi

# ==============================================================================
# 6. DOUBLE-SIDED FILTERING (BEDTOOLS)
# ==============================================================================
echo "Filtering variants using bedtools..."

grep -F "$S1" "$BED_PROBLEMATIC" > relevant_probs.bed
grep -F "$S2" "$BED_PROBLEMATIC" >> relevant_probs.bed
grep -F "$S1" "$BED_GAPS" > relevant_gaps.bed
grep -F "$S2" "$BED_GAPS" >> relevant_gaps.bed

# Stage 1: Filter on Seq1 position (columns 1-3)
# Skip header, build BED from seq1 coords, filter, recover original rows
tail -n +2 "$RAW_STRALN" | \
    awk 'BEGIN{FS=OFS="\t"} {print $1"\t"$2"\t"$3"\t"$0}' > stage1.bed
bedtools intersect -a stage1.bed -b relevant_probs.bed -v > stage1_clean.bed
bedtools intersect -a stage1_clean.bed -b relevant_gaps.bed -v > stage1_final.bed
awk 'BEGIN{FS=OFS="\t"} {for (i=4; i<=NF; i++) printf $i (i==NF?ORS:OFS)}' stage1_final.bed > stage1.tsv

# Stage 2: Filter on Seq2 position (columns 4-6)
awk 'BEGIN{FS=OFS="\t"} {print $4"\t"$5"\t"$6"\t"$0}' stage1.tsv > stage2.bed
bedtools intersect -a stage2.bed -b relevant_probs.bed -v > stage2_clean.bed
bedtools intersect -a stage2_clean.bed -b relevant_gaps.bed -v > stage2_final.bed
awk 'BEGIN{FS=OFS="\t"} {for (i=4; i<=NF; i++) printf $i (i==NF?ORS:OFS)}' stage2_final.bed > stage2.tsv

# Reconstruct TSV with header
head -n 1 "$RAW_STRALN" > filtered_final.tsv
cat stage2.tsv >> filtered_final.tsv

# ==============================================================================
# 7. EXPORT RESULTS
# ==============================================================================
cp "./alignment.aln" "$OUT/${CHR_ID}.aln"
cp -r "./straln_results" "$OUT/straln_raw_all"
cp "./filtered_final.tsv" "$OUT/${CHR_ID}.filtered.tsv"

# Clean up all intermediate scratch files
rm -f alignment.aln ref.fasta mut.fasta \
       relevant_probs.bed relevant_gaps.bed \
       stage1.bed stage1_clean.bed stage1_final.bed stage1.tsv \
       stage2.bed stage2_clean.bed stage2_final.bed stage2.tsv \
       filtered_final.tsv
rm -rf straln_results

echo "Pipeline successful. Results in: $OUT"