import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import os
import argparse
import sys

"""
VCF VARIANT VISUALIZER
----------------------
This script parses a VCF file (specifically one generated by the synthetic
mutation generator) and creates two primary visualizations:
1. A stacked distribution of variant types per chromosome.
2. Boxplots showing the length distribution of Short and Long Indels.
"""


def parse_args():
    """Parses and returns command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Visualize variant distribution and lengths from a VCF file.")
    parser.add_argument("-i", "--input", required=True, help="Path to the input VCF file")
    parser.add_argument("-o", "--out_dir", required=True, help="Directory to save the generated plots")
    return parser.parse_args()


def load_vcf_to_df(filepath):
    """
    Parses VCF lines into a Pandas DataFrame with variant classification.

    Returns:
        Tuple of (DataFrame, error_message). On success, error_message is None.
        On failure, DataFrame is empty and error_message describes the problem.
    """
    if not os.path.exists(filepath):
        return pd.DataFrame(), f"File {filepath} not found."

    rows = []
    with open(filepath, 'r') as f:
        for line in f:
            if line.startswith('#'):
                continue

            fields = line.strip().split('\t')
            if len(fields) < 8:
                continue

            chrom = fields[0]
            ref = fields[3]
            alt = fields[4]
            info = fields[7]

            # Extract length from INFO field (looking for LEN=X)
            length_match = re.search(r'LEN=(\d+)', info)
            if length_match:
                length = int(length_match.group(1))
            else:
                # Manual calculation if LEN tag is missing
                length = abs(len(ref) - len(alt))

            # Variant classification
            if len(ref) == 1 and len(alt) == 1:
                var_type = 'SNP'
            elif len(ref) == len(alt) and len(ref) > 1:
                var_type = 'Substitution'
            elif length <= 50:
                var_type = 'Short Indel'
            else:
                var_type = 'Long Indel'

            rows.append({
                'Chromosome': chrom,
                'Type': var_type,
                'Length': length
            })

    if not rows:
        return pd.DataFrame(), "No valid variant records found in VCF."

    return pd.DataFrame(rows), None


def chrom_key(name):
    """Sorting key to ensure chromosomes appear in order (1, 2, ... X, Y)."""
    parts = re.findall(r'\d+', name)
    num = int(parts[0]) if parts else 99
    return (num, name)


def main():
    args = parse_args()

    os.makedirs(args.out_dir, exist_ok=True)

    # Load and validate data
    df, error = load_vcf_to_df(args.input)
    if error:
        print(f"ERROR: {error}", file=sys.stderr)
        sys.exit(1)

    chrom_order = sorted(df['Chromosome'].unique(), key=chrom_key)

    # Set style once for all plots
    sns.set_style("whitegrid")

    # Plot 1: Distribution by chromosome
    print("Generating variant distribution plot...")
    fig, ax = plt.subplots(figsize=(15, 7))
    sns.countplot(data=df, x='Chromosome', hue='Type', palette='magma',
                  order=chrom_order, ax=ax)

    ax.set_title('Variant Distribution by Chromosome and Type', fontsize=16, pad=20)
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
    ax.set_xlabel('Chromosome / Haplotype', fontsize=12)
    ax.set_ylabel('Number of Variants', fontsize=12)
    ax.legend(title='Variant Type', bbox_to_anchor=(1.01, 1), loc='upper left')
    plt.tight_layout()

    dist_plot_path = os.path.join(args.out_dir, 'variant_distribution.png')
    plt.savefig(dist_plot_path, dpi=300, bbox_inches='tight')
    plt.close()

    # Plot 2: Indel length distribution
    print("Generating indel length distribution plots...")
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    short_data = df[df['Type'] == 'Short Indel']
    long_data = df[df['Type'] == 'Long Indel']

    # Colors sampled from the magma palette: Purple for Short, Orange for Long
    if not short_data.empty:
        sns.boxplot(x='Length', data=short_data, ax=ax1, color='#721f81',
                    width=0.4, boxprops=dict(alpha=0.7), showfliers=False)
        sns.stripplot(x='Length', data=short_data, ax=ax1, color='#2a363b', alpha=0.9, size=5)
    ax1.set_title('Short Indel Length Distribution (≤ 50 bp)', fontsize=14)
    ax1.set_xlabel('Length (bp)', fontsize=12)

    if not long_data.empty:
        sns.boxplot(x='Length', data=long_data, ax=ax2, color='#fe9929',
                    width=0.4, showfliers=False)
        sns.stripplot(x='Length', data=long_data, ax=ax2, color='#2a363b', alpha=0.9, size=5)
    ax2.set_title('Long Indel Length Distribution (≥ 51 bp)', fontsize=14)
    ax2.set_xlabel('Length (bp)', fontsize=12)

    plt.suptitle('Size Distribution of Simulated Indels', fontsize=18, y=1.02)
    plt.tight_layout()

    length_plot_path = os.path.join(args.out_dir, 'indel_lengths_combined.png')
    plt.savefig(length_plot_path, dpi=300, bbox_inches='tight')
    plt.close()

    print("-" * 50)
    print("SUCCESS")
    print(f"Total variants processed: {len(df)}")
    print(f"Distribution plot: {dist_plot_path}")
    print(f"Length plot:       {length_plot_path}")
    print("-" * 50)


if __name__ == "__main__":
    main()