import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import os
import argparse
import sys

"""
VCF VARIANT VISUALIZER
----------------------
This script parses a VCF file (specifically one generated by the synthetic 
mutation generator) and creates two primary visualizations:
1. A stacked distribution of variant types per chromosome.
2. Boxplots showing the length distribution of Short and Long Indels.
"""

def load_vcf_to_df(filepath):
    """Parses VCF lines into a Pandas DataFrame with variant classification."""
    rows = []
    if not os.path.exists(filepath):
        print(f"Error: File {filepath} not found!")
        return pd.DataFrame()

    with open(filepath, 'r') as f:
        for line in f:
            if line.startswith('#'):
                continue

            fields = line.strip().split('\t')
            if len(fields) < 8:
                continue

            chrom = fields[0]
            ref = fields[3]
            alt = fields[4]
            info = fields[7]

            # Extract length from INFO field (looking for LEN=X)
            length_match = re.search(r'LEN=(\d+)', info)
            if length_match:
                length = int(length_match.group(1))
            else:
                # Manual calculation if LEN tag is missing
                length = abs(len(ref) - len(alt))

            # Variant Classification Logic
            if len(ref) == 1 and len(alt) == 1:
                var_type = 'SNP'
            elif len(ref) == len(alt) and len(ref) > 1:
                var_type = 'Substitution'
            elif length <= 50:
                var_type = 'Short Indel'
            else:
                var_type = 'Long Indel'

            rows.append({
                'Chromosome': chrom,
                'Type': var_type,
                'Length': length
            })

    return pd.DataFrame(rows)

def chrom_key(name):
    """Sorting key to ensure chromosomes appear in order (1, 2, ... X, Y)."""
    parts = re.findall(r'\d+', name)
    num = int(parts[0]) if parts else 99
    return (num, name)

def main():
    parser = argparse.ArgumentParser(description="Visualize variant distribution and lengths from a VCF file.")
    parser.add_argument("-i", "--input", required=True, help="Path to the input VCF file")
    parser.add_argument("-o", "--out_dir", required=True, help="Directory to save the generated plots")
    args = parser.parse_args()

    # Create output directory if it doesn't exist
    os.makedirs(args.out_dir, exist_ok=True)

    # --- 1. Data Processing ---
    df = load_vcf_to_df(args.input)

    if df.empty:
        print("Error: DataFrame is empty. Check your input VCF.")
        sys.exit(1)

    chrom_order = sorted(df['Chromosome'].unique(), key=chrom_key)

    # --- 2. Plot 1: Distribution by Chromosome ---
    print("Generating variant distribution plot...")
    plt.figure(figsize=(15, 7))
    sns.set_style("whitegrid")

    # Using the 'magma' palette for a modern scientific aesthetic
    sns.countplot(data=df, x='Chromosome', hue='Type', palette='magma', order=chrom_order)

    plt.title('Variant Distribution by Chromosome and Type', fontsize=16, pad=20)
    plt.xticks(rotation=45, ha='right')
    plt.xlabel('Chromosome / Haplotype', fontsize=12)
    plt.ylabel('Number of Variants', fontsize=12)
    plt.legend(title='Variant Type', bbox_to_anchor=(1.01, 1), loc='upper left')

    plt.tight_layout()
    dist_plot_path = os.path.join(args.out_dir, 'variant_distribution.png')
    plt.savefig(dist_plot_path, dpi=300, bbox_inches='tight')

    # --- 3. Plot 2: Indel Length Distribution ---
    print("Generating indel length distribution plots...")
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
    sns.set_style("whitegrid")

    short_data = df[df['Type'] == 'Short Indel']
    long_data = df[df['Type'] == 'Long Indel']

    # Colors sampled from the magma palette: Purple for Short, Orange for Long
    # Subplot 1: Short Indels
    if not short_data.empty:
        sns.boxplot(x='Length', data=short_data, ax=ax1, color='#721f81', width=0.4, boxprops=dict(alpha=0.7), showfliers=False)
        sns.stripplot(x='Length', data=short_data, ax=ax1, color='#2a363b', alpha=0.9, size=5)
    ax1.set_title('Short Indel Length Distribution (≤ 50 bp)', fontsize=14)
    ax1.set_xlabel('Length (bp)', fontsize=12)

    # Subplot 2: Long Indels
    if not long_data.empty:
        sns.boxplot(x='Length', data=long_data, ax=ax2, color='#fe9929', width=0.4, showfliers=False)
        sns.stripplot(x='Length', data=long_data, ax=ax2, color='#2a363b', alpha=0.9, size=5)
    ax2.set_title('Long Indel Length Distribution (≥ 51 bp)', fontsize=14)
    ax2.set_xlabel('Length (bp)', fontsize=12)

    plt.suptitle('Size Distribution of Simulated Indels', fontsize=18, y=1.02)
    plt.tight_layout()

    length_plot_path = os.path.join(args.out_dir, 'indel_lengths_combined.png')
    plt.savefig(length_plot_path, dpi=300, bbox_inches='tight')

    print("-" * 50)
    print("SUCCESS")
    print(f"Total variants processed: {len(df)}")
    print(f"Distribution plot: {dist_plot_path}")
    print(f"Length plot:       {length_plot_path}")
    print("-" * 50)

if __name__ == "__main__":
    main()